# lightning.pytorch==2.5.1
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices:
  - 0
  num_nodes: 1
  precision: 16-mixed
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: 64
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: ./asl_dvs
  model_registry: null
model:
  P: 2
  H: 180
  W: 240
  h: 9
  w: 12
  embed: neighbor1d-naive2d-2-1
  tpe: add
  d_model: 256
  n_head: 16
  d_feedforward: 512
  n_layers: 2
  t_heads: 1
  n_classes: 24
  classify_head_zero_init: false
  dropout: 0.0
  dropout_sequence: 0.0
  offset_coordinate: false
  offset_t: true
  embed_pretrained: null
  pretrained: null
  learn_head_only: false
  self_supervised: false
  compile: true
  lr: 0.001
  optimizer: adamw
  wd: 0.0
  lrs: CosineAnnealingLR
  label_smoothing: 0.0
  coordinate_noise_std: 0.0
data:
  name: asl_dvs
  root: /dev/shm/ASLDVS/events_np
  sample_number: 255
  sampler: random_sample
  norm_t: dataset-wise
  batch_size: 128
  num_workers: 4
test_only: false
resume: null
optimizer: null
lr_scheduler: null
