seed_everything: 0

trainer:
  default_root_dir: ./asl_dvs
  precision: 32 # bf16-mixed for >= A100
  # precision: 32
  max_epochs: 128

model:
  warmup_epochs: 8
  P: 2
  H: 180
  W: 240
  h: 180
  w: 240
  train_transform_args: ''
  train_transform_policy: ''
  test_transform_args: ''
  backbone: ''
  n_classes: 24
  compile: false
  lr: 5e-4
  min_lr: 1e-6
  optimizer: adamw
  wd: 0.05
  label_smoothing: 0
  batch_size: 64

data:
  name: asl_dvs
  root: /dev/shm/ASLDVS/events_np
  sample_number: 4096
  num_workers: 8
  norm_t: none
  sampler: random_sample
  batch_size: 64