# lightning.pytorch==2.5.3
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices:
  - 0
  num_nodes: 1
  precision: bf16-mixed
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: ./dvslip
      name: lightning_logs
      log_graph: false
      default_hp_metric: true
      prefix: ''
      sub_dir: null
      comment: ''
      purge_step: null
      max_queue: 10
      flush_secs: 120
      filename_suffix: ''
  callbacks: null
  fast_dev_run: false
  max_epochs: 64
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: ./dvslip
  model_registry: null
model:
  P: 2
  H: 128
  W: 128
  h: 128
  w: 128
  train_transform_args: RandomResize-0.8,1.2-0.8,1.2/RandomRotation-128,128-15/RandomShear-0.05,0.05/RandomHorizontalFlip-128-0.5/RandomTranslate-16,16/RandomErasing-128,128-0.1-16,16/RandomChunkDrop-4,128
  train_transform_policy: RandomApply-0.5
  test_transform_args: ''
  d_model: 192
  d_feedforward: 384
  nheads: 6
  n_layers: 16
  activation: 'relu'
  mask_ratio: 0.
  p_token_mix: 0.5
  p_intensity_drop: 0.1
  drop_path: 0.4
  n_classes: 100
  compile: false
  lr: 0.001
  min_lr: 1.0e-06
  batch_size: 64
  warmup_epochs: 4
  optimizer: adamw
  lrs: CosineAnnealingLR
  wd: 0.05
  label_smoothing: 0.1
  load: ./checkpoints/dvs_lip_cluster_event_self_supervised_training.ckpt
  pool_every_layer: 0
data:
  name: dvs_lip
  root: /dev/shm/dvs_lip/kmeans_1024
  sample_number: 1024
  sampler: none
  batch_size: 64
  num_workers: 8
  train_repeats: 3
  val_root: null
  val_sample_number: null
  val_sampler: null
  val_repeats: 1
